overlay images on entities support + autotiling on event/no-random rocks and pits + added 2 entities
Basement-Renovator/Basement-Renovator pull request #243
Opened 2021-05-18 16:04 UTC by SnakeBlock

2021-05-18 16:46 UTC, Zamiell commented
nice work

pr fails black though, can you run black or it, or better yet just set up your IDE to always run black when you save the file

2021-05-24 02:00 UTC, budjmt requested changes
Nice work! Just a few suggestions and questions

2021-05-24 02:00 UTC, budjmt commented on BasementRenovator.py
> +        return override
```suggestion
    def getGfxOverride(self):
        gfxData = self.scene().getBGGfxData()
        if gfxData is None:
            return None

        entID = f"{self.entity.Type}.{self.entity.Variant}.{self.entity.Subtype}"
        return gfxData["Entities"].get(entID)
```

2021-05-24 02:00 UTC, budjmt commented on resources/StagesRepentance.xml
> +			<Entity ID="1000,1009" Image="resources/Backgrounds/rocks_corpse.png" />
I'd rather just be a little repetitive here. It's not a significant enough usability win to justify maintenance imo
```suggestion
			<Entity ID="3000" Image="resources/Backgrounds/pit_corpse.png" />
			<Entity ID="3009" Image="resources/Backgrounds/pit_corpse.png" />
			<Entity ID="1000" Image="resources/Backgrounds/rocks_corpse.png" />
			<Entity ID="1009" Image="resources/Backgrounds/rocks_corpse.png" />
```

2021-05-24 02:00 UTC, budjmt commented on BasementRenovator.py
> +
This is a pretty nice solution! So this is checking if an ent has an override, exit if it's not equal to the current ent's override, else are their base images equal. It seems like you'd want to compare against both used imgs, not just the neighbor's override:
```suggestion
                override = ent.getGfxOverride()
                img = ent.entity.imgPath if override is None else override.get("Image")
                
                return img == pitImg
```

Was there a case this wouldn't be appropriate?

2021-05-24 02:00 UTC, budjmt commented on BasementRenovator.py
> +
Why isn't this also required for rocks?

2021-05-24 04:01 UTC, budjmt requested changes
Sorry one more thing

2021-05-24 04:01 UTC, budjmt commented on BasementRenovator.py
> +                return img == pitImg
sorry am dumb
```suggestion
                img = ent.getCurrentImg()

                if img == pitImg:
                    return True
```

2021-05-24 18:02 UTC, budjmt approved these changes

2021-05-24 18:04 UTC, merged