Ball & Chain + Fissure Spawner + Fix #242
Basement-Renovator/Basement-Renovator pull request #248
Opened 2021-05-22 18:30 UTC by Rchardon

2021-05-22 18:39 UTC, Zamiell commented on BasementRenovator.py
> +                if t in (893, 3001):
no magic numbers! pls fix

2021-05-22 18:40 UTC, Zamiell commented on BasementRenovator.py
> +        if e.Type not in (893, 3001) and e.Subtype >= 255:
should be a previously defined array, don't repeat yourself

2021-05-22 18:40 UTC, Zamiell commented on BasementRenovator.py
> +        if e.Type in (893, 3001):
same here

2021-05-22 18:42 UTC, Zamiell commented on resources/EntitiesRepentance.xml
> +	<entity BaseHP="100" Group="Hosts" ID="3001" Image="resources/Entities/3001.0.0 - Fissure spawner.png" Kind="Enemies" Name="Fissure spawner" Variant="0" Subtype="0" IsGrid="1"/>
shouldn't it be "Fissure Spawner" ? i think that would be more consistent

2021-05-24 01:24 UTC, budjmt requested changes
Nice attention to Qt stuff! I'll think about how this system can be made more generic from an xml perspective

2021-05-24 01:24 UTC, budjmt commented on NicheFeatures.md
> +Some entities like Ball&Chain or Fissure Spawner have editable properties inside the subtype. You can middle-click on the entity to edit its properties.
```suggestion
### Entities with SubType Properties
Some entities (e.g. Ball & Chain and Fissure Spawner) use their SubType to customize their behavior, rather than using it as another variant (e.g. pickups). Middle-click entities to access these customizable properties.
```

2021-05-24 01:24 UTC, budjmt commented on BasementRenovator.py
> +        self.property3 = int(self.binarySubtype[8:12], 2)
Since there being 3 properties will not always be guaranteed, let's do this with a list. Also would be nice to do this directly in bits. Haven't tested this locally but the math *should* be sound...
```suggestion
        self.format = [ 4, 4, 4 ]
        self.properties = [ 0 for i in self.format ]
        subtype = self.entity.Subtype
        for i, numBits in enumerate(self.format)
            self.properties[i] = subtype & (1 << numBits) - 1
            subtype >>= numBits
```

2021-05-24 01:24 UTC, budjmt commented on BasementRenovator.py
> +        mainWindow.scene.update()
```suggestion
    # @pyqtSlot(int)
    def changeProperty(self, index, val):
        self.properties[index] = val
        
        subtype = 0
        for i, numBits in enumerate(reverse(self.format)):
            subtype += self.properties[-(i + 1)] & (1 << numBits) - 1
            subtype <<= numBits

        self.entity.Subtype = subtype 
        mainWindow.dirt()
        mainWindow.scene.update()
```

2021-05-24 01:24 UTC, budjmt commented on BasementRenovator.py
> +            r.currentIndexChanged.connect(self.changeProperty1)
```suggestion
            r.setCurrentIndex(self.properties[0])

            Rotation.setDefaultWidget(r)
            r.currentIndexChanged.connect(lambda x => self.changeProperty(0, x))
```

2021-05-24 01:24 UTC, budjmt commented on BasementRenovator.py
> +
regarding the issue with the context menu reappearing everywhere, why not make this whole class extend QMenu and exec it from the mouse handler? that might make it work

2021-05-24 16:57 UTC, budjmt requested changes

2021-05-24 16:57 UTC, budjmt commented on BasementRenovator.py
> +            QGraphicsItem.mouseReleaseEvent(self, event)
I think we want to process this code regardless, not sure if that causes issues
```suggestion
        self.hideWeightPopup()
        QGraphicsItem.mouseReleaseEvent(self, event)
```

2021-05-28 21:01 UTC, Zamiell commented
gamon is this ready for PR now?

2021-05-28 21:39 UTC, Rchardon commented
yes you can go

2021-05-28 21:39 UTC, Zamiell commented
lets wait for @budjmt to review it

2021-05-29 01:12 UTC, budjmt approved these changes

2021-05-29 01:12 UTC, merged